### ISSUE TITLE
Fix compatibility with built-in encryption mechanism

### ISSUE THREAD

**Issue by ylabonte** [ylabonte/ioBroker.procon-ip#11]
> you added the code to use Auto Adapter encryot/decrypt but you did not provided "encryptedNative" array with the fieldnames in io-package, so most likely there will be NO encryption at all! (changing this will break itfor your users potentially!) Additionally when you do it that way make sure to rename your "own" encrypt/decrypt methods in index_m.ht,l - else they conflict with the ones also build in in Admin
_Originally posted by @Apollon77 in https://github.com/ioBroker/ioBroker.repositories/pull/756#issuecomment-646988248_

**Comment by ylabonte** [comment]
At least I leveraged the built-in encryption mechanism that hard, that the URL, username, and password fields in fact are encrypted using the AES encryption I have implemented in the past. I will fix this; not yet sure, but I think I will do it in a clean way, which will break compatibility to the current AES mechanism. This will lead to an unreadable adapter configuration. So you will have to re-configure the adapter after an update.

**Comment by ylabonte** [comment]
Will be fixed/published with the next release. But this will _as expected_ break settings of existing instances of this adapter.

**Comment by Apollon77** [comment]
In fact we plan to also change the encryption form in js.controller with next release to support AES too ...

**Comment by ylabonte** [comment]
xD Well... that's kind of funny. 

Do you already know which encryption params you will use or if you also use crypto-js (which would be a AES-256 in CBC mode by default)?

So I might roll-back to the AES encryption and only ensure not to collide with the encryption/decryption methods of the admin adapter.

**Comment by Apollon77** [comment]
see https://github.com/ioBroker/ioBroker.js-controller/pull/887/files

**Comment by Apollon77** [comment]
PS: Yes the "frontend part of this" ( so admin support) is still needed to be done, but as we know possible on this basis. More informations @foxriver76 could give

**Comment by ylabonte** [comment]
Okay. I think I'm going to implement it in two steps... 
1. Keep encrypting using XOR, but check for the AES-192 prefix `$/aes-192-cbc:` first when decrypting and using the XOR as fallback in this case.
2. Once the PR on the js-controller is merged/released, I will update my adapter to use the AES-192 for encryption as well and drop the XOR encryption (while keeping the XOR decryption as fallback).

**Comment by Apollon77** [comment]
This will be part of controller 3.2 which should go in public tests beginning September. Depending on results latest and stable then roughly October latest

**Comment by foxriver76** [comment]
Yes, currently this XOR "encryption" is used, so aes192-cbc is only supported up from js-c 3.2 as mentioned by Ingo. aes256-cbc was planned but unique user secrets are only 192bit long, also aes192-cbc should be perfectly fine, otherwise, we would have to create new secrets for every user, which would break some stuff.

**Comment by ylabonte** [comment]
Thanks for all your input! 

I've started to re-work the backend part. But I am not really clear on how to implement this encryption browser-side as it depends on the node-js/server-side `crypto` module..? I think I will use [CryptoJS](https://cryptojs.gitbook.io/docs/#the-cipher-input) for the frontend again, as it seems capable of also handling an actual key with initialization vector instead of a passphrase, as I have used it before.

**Comment by ylabonte** [comment]
I tried to achieve the frontend implementation using the native `window.crypto` class, but ended up rolling back to CryptoJS. The decisive factor was the following error message which I received during my last attempts with the JS native approach: 
```
Uncaught (in promise) DOMException: 192-bit AES keys are not supported
```

The solution using CryptoJS will look something like this:
```js
// Plaintext encrypted using the aes-192-cbc implementation of the js-controller was "Hello World!".
// The output of the backend encryption process was:
const cipher = '$/aes-192-cbc:8b6ddb7ca33ccd770f3bbfca48d4ff78:7e1fd9ebf2f87604dc689862db7c74fe';
// The secret 192-bit key in hex representation is:
const secretKey = '1234567890abcdef1234567890abcdef1234567890abcdef';

// Prepare decryption
const cipherParts = encrypted.split(':');
const cipherText = CryptoJS.enc.Hex.parse(cipherParts[2]);
const iv = CryptoJS.enc.Hex.parse(cipherParts[1]);
const key = CryptoJS.enc.Hex.parse(secretKey);

// Actually decrypt the cipher text
const decrypter = CryptoJS.algo.AES.createDecryptor(key, { iv: iv });
const plaintext = decrypter.process(cipherText);
plaintext.concat(decrypter.finalize());

// Log the result to console...
console.log(plaintext.toString(CryptoJS.enc.Utf8));
```

The corresponding commit will follow soon.


@foxriver76 
> Yes, currently this XOR "encryption" is used, so aes192-cbc is only supported up from js-c 3.2 as mentioned by Ingo. aes256-cbc was planned but unique user secrets are only 192bit long, also aes192-cbc should be perfectly fine, otherwise, we would have to create new secrets for every user, which would break some stuff.
> 
> Admin: [ioBroker/ioBroker.admin#598](https://github.com/ioBroker/ioBroker.admin/issues/598)

By the way: CryptoJS would be capable of using any string as key material input (passphrase), generate a 256-bit key from the input and so apply aes-256-cbc in a one-liner, regardless of any restrictions to the key length... So the whole encryption/decryption process could look like this:
```js
var encrypted = CryptoJS.AES.encrypt("Message", "Secret Passphrase");
var decrypted = CryptoJS.AES.decrypt(encrypted, "Secret Passphrase");
```
And with thanks to the CryptoJS abstraction of the native javascript frontend and backend crypto methods, it would be the same for both environments. No idea, if this could be an option for the future, just wanted to have it mentioned...

**Comment by ylabonte** [comment]
I think, this ticket can be closed now. Feel free to review or comment on the appropriate pull request (#16).
