### ISSUE TITLE
Add node 18 tests / verify functionality with node 18 OR require node 20 minimum

### ISSUE THREAD

**Issue by mcm1957** [ylabonte/ioBroker.procon-ip#113]
Current package.json specifies node 18 as minimum required node version.
Your github based tests are executed at node 20 and 22 only. 

So either node 18 must be added to testmatrix OR the requirement muts be raised to node 20 minimum.

NOTE:
At my fork tests with node 18 FAIL:
error rimraf@6.0.1: The engine "node" is incompatible with this module. Expected version "20 || >=22". Got "18.20.4"
see https://github.com/mcm1957/ioBroker.procon-ip/actions/runs/10753825671/job/29823713257

So most likely the required node version must be raised to 20.
Please note that raising node (or other dependency requirements) require a new MINOR version at least.

**Please check and fix and create a new (minor ?) version if raising node requirements is necessary.**

**Comment by ylabonte** [comment]
Version 1.6.0 has been released. Waiting another 14+ days before declaring it as stable...
