### ISSUE TITLE
Warnung "has no existing object, this might lead to an error in future version"

### ISSUE THREAD

**Issue by csr-1-0** [ylabonte/ioBroker.procon-ip#21]
Hallo yannic,

gibt es wegen der Fehlermeldungen was neues?
Besteht ja schon länger, oder soll die Log-Ausgabe weiterhin mit error eingestellt bleiben um die Log- Datei nicht komplett "zuzuspamen" ;-) ?
Hab im Controller-Forum auch nochmal geschrieben, da ist irgendwie Stillstand.

```
procon-ip.0 | 2021-04-18 11:23:31.385 | warn | (1588) State "procon-ip.0.temperatures.1.offset" has no existing object, this might lead to an error in future versions
procon-ip.0 | 2021-04-18 11:23:31.384 | warn | (1588) State "procon-ip.0.temperatures.1.id" has no existing object, this might lead to an error in future versions
procon-ip.0 | 2021-04-18 11:23:31.383 | warn | (1588) State "procon-ip.0.analog.4.categoryId" has no existing object, this might lead to an error in future versions
procon-ip.0 | 2021-04-18 11:23:31.383 | warn | (1588) State "procon-ip.0.analog.4.raw" has no existing object, this might lead to an error in future versions
```

... ... usw. usw. dürfte ja bekannt sein.

**Comment by ylabonte** [comment]
Sorry, dass es so lang gedauert hat, aber ist jetzt mit dem aktuellen [Release v1.1.1](https://github.com/ylabonte/ioBroker.procon-ip/releases/tag/v1.1.1) behoben.
