### ISSUE TITLE
Changelog Headers are duplicated

### ISSUE THREAD

**Issue by mcm1957** [ylabonte/ioBroker.procon-ip#70]
Please remove duplicate changelog headers at README.md if time allows. (Most likely copy & Paste result :-) )

https://github.com/ylabonte/ioBroker.procon-ip/tree/master?tab=readme-ov-file#changelog-1

**Comment by ylabonte** [comment]
Sorry, I'm not entirely sure how I did that, but thanks for pointing it out! 😃

It's fixed on the `master` branch now.

I am not sure that the display within ioBroker has been fixed yet. But I will prepare a new release with updated dev dependencies for the `latest` repository in the next few days and publish it as `stable` 14 days later. By then, at the latest, the changelog should be displayed correctly in all places again.
